name: gigamidi
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - GitPython==3.1.46
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PySocks==1.7.1
    - PyYAML==6.0.3
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - anyio==4.12.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - beautifulsoup4==4.14.3
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - contourpy==1.3.2
    - csrgraph==0.1.28
    - cycler==0.12.1
    - datasets==4.4.2
    - dill==0.4.0
    - einops==0.8.1
    - einx==0.3.0
    - exceptiongroup==1.3.1
    - filelock==3.20.3
    - fonttools==4.61.1
    - frozendict==2.4.7
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - gdown==5.2.1
    - gensim==4.4.0
    - gitdb==4.0.12
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - joblib==1.5.3
    - kiwisolver==1.4.9
    - llvmlite==0.46.0
    - matplotlib==3.10.8
    - miditoolkit==1.0.1
    - mido==1.3.3
    - mpmath==1.3.0
    - multidict==6.7.0
    - multiprocess==0.70.18
    - networkx==2.8.8
    - nodevectors==0.1.23
    - numba==0.63.1
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.8.90
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.1.0
    - platformdirs==4.5.1
    - propcache==0.4.1
    - protobuf==6.33.3
    - pySmartDL==1.3.4
    - pyarrow==22.0.0
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - pyparsing==3.3.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - regex==2025.11.3
    - requests==2.32.5
    - safetensors==0.7.0
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentry-sdk==2.49.0
    - shellingham==1.5.4
    - six==1.17.0
    - smart_open==7.5.0
    - smmap==5.0.2
    - soupsieve==2.8.1
    - sympy==1.14.0
    - symusic==0.5.9
    - threadpoolctl==3.6.0
    - tokenizers==0.22.2
    - torch==2.9.1
    - tqdm==4.67.1
    - transformers==4.57.3
    - triton==3.5.1
    - typer-slim==0.21.1
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.3
    - vector-quantize-pytorch==1.27.16
    - wandb==0.23.1
    - wrapt==2.1.1
    - xxhash==3.6.0
    - yarl==1.22.0

prefix: "/data3/pnlong/micromamba/envs/gigamidi"
